---
layout: single
title: "깃허브 push 오류"
---

# 로컬저장소에서 원격저장소로 push가 되지 않는 현상
여느때와 다름없이 작업을 하고 push를 했는데 에러가 뜨면서 push가 되지 않는다

원인:1.브랜치 연결이 끊겨있었음 2.서로 다른 브랜치에 있어서 push 를 해도 반영되지 않음

## 해결방법

먼저 서로 다른 브랜치 이름을 가지고 있어서 로컬 브랜치 이름을 변경해주었다
git branch -m master main  master -> main 으로 이름 변경

저장소 최신 변경 사항을 가져온다
git fetch origin

로컬의 'main' 브랜치를 원격 저장소(origin)의 'main' 브랜치와 연결(tracking)하는 명령어
git branch -u origin/main main

브랜치 연결 상태를 확인 
git branch -vv ->'main' 브랜치가 원격 저장소(origin)의 'main' 브랜치와 연결되어 있을 경우, 'main [origin/main]'과 같이 표시됨

에러 2
"fatal: refusing to merge unrelated histories"

pull 을 하니 두 브랜치의 커밋 이력이 완전히 달라서 관련이 없다고 판단하고 병합을 거부하는 오류가 발생했다.
git pull origin main --allow-unrelated-histories -> 커밋 이력이 달라도 병합하는 명령어

다시 push를 해보니 변경사항이 깃허브에 잘 반영된다